spring:
  zipkin:
    base-url: http://192.168.247.111:9411/  #zipkin 服务器地址
    discovery-client-enabled: false #关闭服务发现,否则springcloud 会把zipkin 的url当做服务名称
    sender:
      type: web #设置http的访问方式
  sleuth:
    sampler:
      rate: 1 #设置抽样采集率为 1000% 默认为0.1 即10%
  application:
    name: gulimail-third-party  #服务名
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8333
    nacos:
      discovery:
        server-addr: 47.103.16.140:8848   #服务注册进服务中心

server:
  port: 3388  #定义端口号

alibaba:
  cloud:
    access-key: LTAI4G3fDrcjcGsm691wF7Az
    secret-key: vuZ4qZHAqeYSGQoN7dmS979KpJ92Nq
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket: gulimail-zgx
  sms:
    host: https://gyytz.market.alicloudapi.com
    path: /sms/smsSend
    method: POST
    appcode: b247c3585f934123ba122aec1a83178c
    smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
    templateId: 63698e3463bd490dbc3edc46a20c55f5


#暴露全部端口
management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    com.atguigu.gulimail: debug  #打印debut日志