spring:
  application:
    name: gulimail-third-party  #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.247.111:8848   #服务注册进服务中心

server:
  port: 3388  #定义端口号

alibaba:
  cloud:
    access-key: LTAI4G3fDrcjcGsm691wF7Az
    secret-key: vuZ4qZHAqeYSGQoN7dmS979KpJ92Nq
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket: gulimail-zgx