# DataSource Config
spring:
  zipkin:
    base-url: http://192.168.247.111:9411/  #zipkin 服务器地址
    discovery-client-enabled: false #关闭服务发现,否则springcloud 会把zipkin 的url当做服务名称
    sender:
      type: web #设置http的访问方式
  sleuth:
    sampler:
      rate: 1 #设置抽样采集率为 1000% 默认为0.1 即10%
  redis:
    host: 192.168.247.111 #配置reids
    port: 6379
  session:
    store-type: redis
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8333
    nacos:
      discovery:
        server-addr: 47.103.16.140:8848
      config:
        server-addr: 47.103.16.140:8848
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}-fescar-service-group
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual  #手动消息接收
    host: 192.168.247.111  #配置rabbitmq 的IP地址
    username: guest
    password: guest
    port: 5672
    virtual-host: /  #虚拟主机
    publisher-confirm-type: CORRELATED  #发送端确认模式
    publisher-returns: true #开启发送消息抵达队列确认
    template:
      mandatory: true #如果抵达了这个队列 以异步方法优先回调这个 returnCallback 方法
  application:
    name: gulimail-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.16.140:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Abc123!_
  thymeleaf:
    cache: false #模式缓存 设置为false
server:
  port: 9000
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";


domain:
  name:
    domainName: gulimail.com #顶级父域名 因为现在在auth.gulimail.com 顶级域名为 gulimail.com 全局生效
    cookieName: GULIMAIL_SESSION  #cookie在本地显示的名称可以随便设置


#配置线程池
gulimail:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10


#支付配置
alipay:
  appId: 2021000117622244
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDVYZgjRnSACgoIWL8JK9VJAlICAOli9kMGrfQslZttWo4EFa+BGMREPzNhYAj57K5oPWGJ8ekM+LXBSa27N5Glwh/CO5Lv/YNNDO1qhnktO1zYim9FLzwS4uctdfucutN2XIcvActAnd2Ci9E5WHF+9f/2B0iVYIk4ElaWgbOGQRRWE1vi5G/33wl/TlWrsmCXOa4/kcZDJTH8DflsIpJFyniw6hl5nDCXZKCXiqs/uw0e88kwOMFfadWpV9mr1FNt7meUBiL/tfbMzgZmZki4MaJXw1d5NBDzMLNKouMENCDlUpOjS1XeOx5x822H7ypTwkhjzH5iTT/RLO2PkPx5AgMBAAECggEBAM93HFzv28XB/Q8wek2IeM+LmgCoskKt/W05JPdUXtJsATinfQSf9/QDHwnGPfQB03E2fOeKdXVPPCi6YlhtJwdrP0WydqMwccEwmIXCSX9ZAGTp9FXoHxid1Pe2hvVUENY8EJP7wosI8p5DIyIGhBNVS5ECc+gI/GGwMtATO2GDjqUfKPDCgy2b+jncFg0hfUr/c3COsGzLnVGCXa8AKMZaoKhEYmtWymf3g1C6y6nrFLOITU99tKXhfOLUa3I8eXg1hqk+8Hq1sVz4gNhMmFzs4uo/YhH1Whvfmoep1p3zs1S65gj8L69hnEdIy+nXIoP74LpmcXm5T3qUtg/afAECgYEA7HHHs3AtnkwI37oV5Mic7cje5zQeCc52/6uWnPMZSXDzkFw5owg1Po/js9fzRoBwihviWi47sChf3bBsu4a/JQJMxDpSqkUtHCUPXMbjuAr4PnOtnk0CZ9YNRynUOsBlUTEXS6ZOt9riuALtSii4v+hqNlcOVJLhyKZfX6tbeMkCgYEA5wd/kqg24jDm8PRYa9YJWpYOrMDxDGhauAfk3hclBdL+aY59cdkVOI0CDXdxe2tour/Xi4RvaCxPvBvySsLs9WJYx6Rfk+F/ESewZqOJspxs+f25TT0y3ZgyqddQ9lXUVZmgUffmTxfxNsw2HHu1g6tXqnetkC1rfiiBDpik7jECgYAl/XoayLFrt8fNOrb91YXxZs750xPoe3X/SnCesyii9jUMQuU33r+/V5s8cDw0Xbq3VheeacNJYJNWqVwvHU1lAuOWu9BAb3D6DrJTM9mu3oRYdHm276StTmU/w+bHsdYVn4+gpg4L2G2JJ189BSH6I7u9E2vIBvmkJac5Ve0SkQKBgClyCevYa4gmd7ewThCCZEkw9E7/if7M1cGAAQnqowSpdmSfYFfFNu5fNYgO7nfSrAYclmF8D7RjhqZbaRsKXxIiY4TlMxRHdtEwCpBPNEurjk1GvDBkEzT3sdcQPoECosX8emtaCqITzH0lI2v2sXh+i4qUT7m2vDr0rzpcHfJxAoGAPtG/ah9D5klLA5fLGCvyYPm5RWKHf8D+cB+oEbpxvuy4f80fLVsn1lEx5MhnlV4IT3m+KKDPHYO2A1LyKGe+CrJU8DxkMzfDAyxggXsvXPvk0jSxuhvvN5vQU7r7U/54oxYeFagi/sl+8eFYIZQI1oOfBLakBfk4Lux3LAT+bII=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArcMdvkV53f5i1k5t2oS5cp58YLzjvf0YFBPZD2BZFaFsstknOUgqK60rYJhi9cXUNOyDKnUAOlj33ljIsUp+/UiAnp/0p8RvFuD3fYBMdWW2I53ZlIHwU25t8QXwZG1Ha3GX81O45hWzWdj9jASJxJ2FjMfZwIun8D6zbpt2LIHPM0jFKewxp4NWHeB1u/7N7S7Dr/Tr25suKkXuD7csxEmiJ4dIREskH+ZUu7b4pOpCPK4BH4XIh4GEoeJa5k/mztPm20WCHVHKR6pT7krSvsxGQYeKRgALAGDQ/ec2ahphlrkOgk6RiiGz00CrgdInPHTeDDwE00CPSWh9A71LoQIDAQAB
  notifyUrl: http://cp2xftcfdv.52http.tech/payed/notity
  returnUrl: http://order.gulimail.com/list.html
  signType: RSA2
  charSet: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  timeExpire: 1m


#暴露全部端口
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    com.atguigu.gulimail: debug  #打印debut日志