# DataSource Config
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #格式化json时间
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8333
    nacos:
      config:
        server-addr: 47.103.16.140:8848   #注册进中心
      discovery:
        server-addr: 47.103.16.140:8848   #服务注册进服务中心
    alibaba:
      seata:
        tx-service-group: ${spring.application.name}-fescar-service-group
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual #手动消息接收
    host: 192.168.247.111
    username: guest
    password: guest
    port: 5672
    virtual-host: /  #虚拟主机
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.16.140:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Abc123!_
  application:
    name: gulimail-ware
server:
  port: 11000
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";

logging:
  level:
    com.atguigu.gulimail: debug  #打印debut日志


#暴露全部端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true