spring:
  session:
    store-type: redis
  redis:
    host: 192.168.247.111
    port: 6379
  application:
    name: gulimail-elasticsearch
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8333
    nacos:
      discovery:
        server-addr: 47.103.16.140:8848  #配置Nacos 的IP地址
  thymeleaf:
    cache: false #关闭 thymeleaf 缓存实时查看效果
server:
  port: 12000
domain:
  name:
    domainName: gulimail.com #顶级父域名 因为现在在auth.gulimail.com 顶级域名为 gulimail.com 全局生效
    cookieName: GULIMAIL_SESSION  #cookie在本地显示的名称可以随便设置


#暴露全部端口
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true