spring:
  session:
    store-type: redis
  application:
    name: gulimail-autu-server
  redis:
    host: 192.168.247.111  #配置redis
    port: 6379
    database: 0
  cloud:
    nacos: #配置nocos 注册中心
      discovery:
        server-addr: 47.103.16.140:8848
  thymeleaf:
    cache: false
server:
  port: 20000
  servlet:
    session:
      timeout: 30m #session 存活时间
domain:
  name:
    domainName: gulimail.com #顶级父域名 因为现在在auth.gulimail.com 顶级域名为 gulimail.com 全局生效
    cookieName: GULIMAIL_SESSION  #cookie在本地显示的名称可以随便设置
    root-url: http://gulimail.com
    son-login-url: http://auth.gulimail.com/login.html
    son-register-url: http://auth.gulimail.com/register.html
github:
  configure:
    clientId: 7a5fefb44152bc4299e7
    clientSecret: 0fc96714c439204c3327218493c2aca1d8c1cf03
    callback: http://auth.gulimail.com/github/callback